from address import get_balance

TOTAL_SUPPLY = 100000000000
DESTROYED_ADDRESS = "NEW182E111111111111111111111111114FhDeS"
LOCK_COMMUNITY_0 = "NEW182DJKw4XF7Wf5ydR2jgsKE4MEsAE4u1XwzY"
LOCK_COMMUNITY_1 = "NEW182GmTCCigKUaPrS2QsYjgExZRUK6J25ebKv"
LOCK_COMMUNITY_NODE = "NEW182W9mbuWDmewyErARX5qVu9hd5gmyLh3E4n"
LOCK_COMMUNITY_POOL = "NEW182EccTcNzqj69UanWZwuyecnPX9LCNfJabc"

print(f"Total Supply:\t\t {TOTAL_SUPPLY}")

DESTROYED_AMOUNT = get_balance(DESTROYED_ADDRESS)
MAX_SUPPLY = TOTAL_SUPPLY - DESTROYED_AMOUNT
print(f"Max Supply:\t\t {MAX_SUPPLY}")

LOCK_COMMUNITY_0_AMOUNT = get_balance(LOCK_COMMUNITY_0)
LOCK_COMMUNITY_1_AMOUNT = get_balance(LOCK_COMMUNITY_1)
LOCK_COMMUNITY_NODE_AMOUNT = get_balance(LOCK_COMMUNITY_NODE)
LOCK_COMMUNITY_POOL_AMOUNT = get_balance(LOCK_COMMUNITY_POOL)

CIRCULATING_SUPPLY = (
    MAX_SUPPLY
    - LOCK_COMMUNITY_0_AMOUNT
    - LOCK_COMMUNITY_1_AMOUNT
    - LOCK_COMMUNITY_NODE_AMOUNT
    - LOCK_COMMUNITY_POOL_AMOUNT
)
print(f"Circulating Supply:\t {CIRCULATING_SUPPLY}")
